winget list

winget uninstall "Microsoft Get Help"
winget uninstall "Microsoft Phone Link"
winget uninstall "Windows Backup"
winget uninstall "Dev Home"
winget uninstall "Cross Device Experience Host"
winget uninstall "Xbox Identity Provider"
winget uninstall "Xbox Game Bar"
winget uninstall "Xbox Console Companion"
winget uninstall "Xbox TCUI"
winget uninstall "Microsoft Teams"
winget uninstall "Microsoft To Do"
winget uninstall "Microsoft OneDrive"
winget uninstall "Cortana"
winget uninstall "Your Phone"
winget uninstall "Microsoft People"
winget uninstall "Solitaire & Casual Games"
winget uninstall "Microsoft Bing News"
winget uninstall "Microsoft Bing Weather"
winget uninstall "Microsoft Feedback Hub"
winget uninstall "Microsoft Clipchamp"
winget uninstall "Microsoft 3D Viewer"
winget uninstall "Mixed Reality Portal"
winget uninstall "Microsoft.BingNews_8wekyb3d8bbwe"
winget uninstall "Microsoft.Copilot_8wekyb3d8bbwe"
winget uninstall "Microsoft.Edge.GameAssist_8wekyb3d8bbwe"
winget uninstall "Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe"
winget uninstall "Microsoft.OneDriveSync_8wekyb3d8bbwe"
winget uninstall "Microsoft.XboxGamingOverlay_8wekyb3d8bbwe"
winget uninstall "Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe"
winget uninstall "Microsoft.YourPhone_8wekyb3d8bbwe"
winget uninstall "Microsoft.ZuneMusic_8wekyb3d8bbwe"
winget uninstall "MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe"
winget uninstall "Microsoft.WindowsCamera_8wekyb3d8bbwe"
winget uninstall "Microsoft.WindowsAlarms_8wekyb3d8bbwe"
winget uninstall "Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe"
winget uninstall "Microsoft.OutlookForWindows_8wekyb3d8bbwe"
winget uninstall "Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe"
winget uninstall "Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe"
winget uninstall "Microsoft.GetHelp_8wekyb3d8bbwe"
winget uninstall "Microsoft.GamingApp_8wekyb3d8bbwe"
winget uninstall "Microsoft.Edge.GameAssist_8wekyb3d8bbwe"
winget uninstall "Microsoft.Copilot_8wekyb3d8bbwe"
winget uninstall "Microsoft.BingWeather_8wekyb3d8bbwe"
winget uninstall "Microsoft.BingSearch_8wekyb3d8bbwe"
winget uninstall "Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe"
winget uninstall "Microsoft.VP9VideoExtensions_8wekyb3d8bbwe"
winget uninstall "Microsoft.WebMediaExtensions_8wekyb3d8bbwe"
winget uninstall "Microsoft.Winget.Source_8wekyb3d8bbwe"
winget uninstall "MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy"
winget uninstall "Microsoft.StorePurchaseApp_8wekyb3d8bbwe"
winget uninstall "Microsoft.RawImageExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.AV1VideoExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.AVCEncoderVideoExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.HEIFImageExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.HEVCVideoExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.MPEG2VideoExtension_8wekyb3d8bbwe"
winget uninstall "Microsoft.ApplicationCompatibilityEnhancements_8wekyb3d8bbwe"
winget uninstall "Microsoft.Winget.Source_8wekyb3d8bbwe"
winget uninstall "MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe"
winget uninstall "MSIX\Microsoft.Winget.Source_2025.1003.2152.56_neutral__8wekyb3d8bbwe"
 winget uninstall "MSIX\Microsoft.StartExperiencesApp_1.140.0.0_x64__8wekyb3d8bbwe"
